#ifndef __PhotoOrganizerFrame__
#define __PhotoOrganizerFrame__

/**
@file
Subclass of Frame, which is generated by wxFormBuilder.
*/

#include "PhotoOrganizer.h"

//// end generated include

/** Implementing Frame */
class PhotoOrganizerFrame : public Frame
{
protected:
	// Handlers for Frame events.
	void m_loadFolderOnButtonClick(wxCommandEvent& event);
	void m_maxHeightControlOnSpinCtrl(wxSpinEvent& event);
	void m_maxHeightControlOnSpinCtrlText(wxCommandEvent& event);
	void m_maxHeightControlOnTextEnter(wxCommandEvent& event);
	void m_maxWidthControlOnSpinCtrl(wxSpinEvent& event);
	void m_maxWidthControlOnSpinCtrlText(wxCommandEvent& event);
	void m_maxWidthControlOnTextEnter(wxCommandEvent& event);
	void m_compressiomLevelOnSlider(wxCommandEvent& event);
	void m_folderNameOnText(wxCommandEvent& event);
	void m_exportOnButtonClick(wxCommandEvent& event);
public:
	/** Constructor */
	PhotoOrganizerFrame(wxWindow* parent);
	//// end generated class members


	wxString sourcePath = "";
	wxString targetPath = "";
	wxArrayString JPGfiles = wxArrayString();
	wxArrayString BMPfiles = wxArrayString();
	int JPGcount = 0;
	int BMPcount = 0;
	int compressionValue = 50;
};

#endif // __PhotoOrganizerFrame__
