#ifndef __PhotoOrganizerFrame__
#define __PhotoOrganizerFrame__

/**
@file
Subclass of Frame, which is generated by wxFormBuilder.
*/

#include "PhotoOrganizer.h"

//// end generated include
#include <wx/wx.h>
#include <wx/dir.h>
#include <wx/string.h>
#include <wx/filefn.h> 
#include <string>
#include "FreeImage.h"

/** Implementing Frame */
class PhotoOrganizerFrame : public Frame
{
protected:
	// Handlers for Frame events.
	void m_loadFolderOnButtonClick(wxCommandEvent& event);
	void m_maxHeightControlOnSpinCtrl(wxSpinEvent& event);
	void m_maxHeightControlOnSpinCtrlText(wxCommandEvent& event);
	void m_maxHeightControlOnTextEnter(wxCommandEvent& event);
	void m_maxWidthControlOnSpinCtrl(wxSpinEvent& event);
	void m_maxWidthControlOnSpinCtrlText(wxCommandEvent& event);
	void m_maxWidthControlOnTextEnter(wxCommandEvent& event);
	void m_compressiomLevelOnSlider(wxCommandEvent& event);
	void m_folderNameOnText(wxCommandEvent& event);
	void m_exportOnButtonClick(wxCommandEvent& event);
public:
	/** Constructor */
	PhotoOrganizerFrame(wxWindow* parent);
	//// end generated class members

	const wxArrayString getAllFilesInDirWithExtension(const wxDir& dir, const wxString extension) const;
	void copyAll_JPG(wxString& currPath, wxString& targetPath) const;
	void copyAll_PNG(wxString& currPath, wxString& targetPath) const;
	void cloneDir(wxString& source, wxString& target) const;

	wxString sourcePath = "";
	// wxString targetPath = "";
	wxArrayString &JPGfiles = wxArrayString();
	wxArrayString &BMPfiles = wxArrayString();
	wxArrayString &PNGfiles = wxArrayString();
	int JPGcount = 0;
	int BMPcount = 0;
	int compressionValue = 50;
};

#endif // __PhotoOrganizerFrame__
